config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)

    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="form-group">
  <%= form_for(article) do |t| %>
    <%= t.label :title %>
    <%= t.text_field :title %>
    <%= t.label :content %>
    <%= t.text_field :content %>
    <%= t.submit %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<nav class="navbar navbar-light bg-light" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header"><%= link_to "Wikinimous", articles_path %></div>
    <div class="navbar-header"><%= link_to "Add a new article", new_article_path %></div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <h1>Editing article</h1>

      <%= render "form", article: @article %>

    </div>
  </div>
</div>

app/views/articles/index.html.erb
<h1>My articles</h1>


<% @articles.each do |article| %>
  <h4><%= link_to article.title, article_path(article) %></h4>
  <p><%= article.content %></p>
<% end %>


<%= link_to "Add a new article", new_article_path %>

app/views/articles/new.html.erb
<nav class="navbar navbar-light bg-light" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header"><%= link_to "Wikinimous", articles_path %></div>
    <div class="navbar-header"><%= link_to "Add a new article", new_article_path %></div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <h1>New article</h1>

      <%= render "form", article: @article %>

    </div>
  </div>
</div>

app/views/articles/show.html.erb
<nav class="navbar navbar-light bg-light" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header"><%= link_to "Wikinimous", articles_path %></div>
    <div class="navbar-header"><%= link_to "Add a new article", new_article_path %></div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1><%= @article.title %>
        <small>
          <%= link_to edit_article_path do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        </small>
        <small>
          <%= link_to article_path(@article),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </small>
      </h1>
      <p><%= @article.content %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>